micronaut:
  application:
    name: jobApplicationsAuthorization
  security:
    authentication: cookie
    oauth2:
      clients:
        default:
          client-id: ${OAUTH_CLIENT_ID}
          client-secret: ${OAUTH_CLIENT_SECRET}
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
netty:
  default:
    allocator:
      max-order: 3
kafka.bootstrap.servers: localhost:9092
